[theme]

# Primary accent for interactive elements
primaryColor = '#F1E0E8'

# Background color for the main content area
backgroundColor = '#ECC7F1'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F160F1'

# Color used for almost all text
textColor = '#00023D'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"